/*
 * This file is generated by jOOQ.
 */
package cs499.data_classes;


import cs499.data_classes.tables.Course;
import cs499.data_classes.tables.Question;
import cs499.data_classes.tables.QuestionBank;
import cs499.data_classes.tables.Quiz;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_COURSE_API_ID = Internal.createIndex(DSL.name("idx_course_api_id"), Course.COURSE, new OrderField[] { Course.COURSE.API_ID }, true);
    public static final Index IDX_QUESTION_API_ID = Internal.createIndex(DSL.name("idx_question_api_id"), Question.QUESTION, new OrderField[] { Question.QUESTION.API_ID }, true);
    public static final Index IDX_QUESTION_BANK_API_ID = Internal.createIndex(DSL.name("idx_question_bank_api_id"), QuestionBank.QUESTION_BANK, new OrderField[] { QuestionBank.QUESTION_BANK.API_ID }, true);
    public static final Index IDX_QUESTION_BANK_QTI_ID = Internal.createIndex(DSL.name("idx_question_bank_qti_id"), QuestionBank.QUESTION_BANK, new OrderField[] { QuestionBank.QUESTION_BANK.QTI_ID }, true);
    public static final Index IDX_QUESTION_QTI_ID = Internal.createIndex(DSL.name("idx_question_qti_id"), Question.QUESTION, new OrderField[] { Question.QUESTION.QTI_ID }, true);
    public static final Index IDX_QUIZ_API_ID = Internal.createIndex(DSL.name("idx_quiz_api_id"), Quiz.QUIZ, new OrderField[] { Quiz.QUIZ.API_ID }, true);
    public static final Index IDX_QUIZ_QTI_ID = Internal.createIndex(DSL.name("idx_quiz_qti_id"), Quiz.QUIZ, new OrderField[] { Quiz.QUIZ.QTI_ID }, true);
}
