/*
 * This file is generated by jOOQ.
 */
package cs499.data_classes;


import cs499.data_classes.tables.BankQuestions;
import cs499.data_classes.tables.Course;
import cs499.data_classes.tables.GroupQuestions;
import cs499.data_classes.tables.Instructor;
import cs499.data_classes.tables.Question;
import cs499.data_classes.tables.QuestionBank;
import cs499.data_classes.tables.QuestionGroup;
import cs499.data_classes.tables.QuestionReferences;
import cs499.data_classes.tables.Quiz;
import cs499.data_classes.tables.QuizQuestions;
import cs499.data_classes.tables.QuizReferences;
import cs499.data_classes.tables.ReferenceMaterial;
import cs499.data_classes.tables.Section;
import cs499.data_classes.tables.records.BankQuestionsRecord;
import cs499.data_classes.tables.records.CourseRecord;
import cs499.data_classes.tables.records.GroupQuestionsRecord;
import cs499.data_classes.tables.records.InstructorRecord;
import cs499.data_classes.tables.records.QuestionBankRecord;
import cs499.data_classes.tables.records.QuestionGroupRecord;
import cs499.data_classes.tables.records.QuestionRecord;
import cs499.data_classes.tables.records.QuestionReferencesRecord;
import cs499.data_classes.tables.records.QuizQuestionsRecord;
import cs499.data_classes.tables.records.QuizRecord;
import cs499.data_classes.tables.records.QuizReferencesRecord;
import cs499.data_classes.tables.records.ReferenceMaterialRecord;
import cs499.data_classes.tables.records.SectionRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BankQuestionsRecord> BANK_QUESTIONS__ = Internal.createUniqueKey(BankQuestions.BANK_QUESTIONS, DSL.name(""), new TableField[] { BankQuestions.BANK_QUESTIONS.QUESTION_ID, BankQuestions.BANK_QUESTIONS.BANK_ID }, true);
    public static final UniqueKey<CourseRecord> COURSE__ = Internal.createUniqueKey(Course.COURSE, DSL.name(""), new TableField[] { Course.COURSE.ID, Course.COURSE.TITLE }, true);
    public static final UniqueKey<GroupQuestionsRecord> GROUP_QUESTIONS__ = Internal.createUniqueKey(GroupQuestions.GROUP_QUESTIONS, DSL.name(""), new TableField[] { GroupQuestions.GROUP_QUESTIONS.QUESTION_ID, GroupQuestions.GROUP_QUESTIONS.GROUP_ID }, true);
    public static final UniqueKey<InstructorRecord> INSTRUCTOR__ = Internal.createUniqueKey(Instructor.INSTRUCTOR, DSL.name(""), new TableField[] { Instructor.INSTRUCTOR.ID, Instructor.INSTRUCTOR.EMAIL }, true);
    public static final UniqueKey<QuestionRecord> QUESTION__ = Internal.createUniqueKey(Question.QUESTION, DSL.name(""), new TableField[] { Question.QUESTION.ID, Question.QUESTION.ID }, true);
    public static final UniqueKey<QuestionBankRecord> QUESTION_BANK__ = Internal.createUniqueKey(QuestionBank.QUESTION_BANK, DSL.name(""), new TableField[] { QuestionBank.QUESTION_BANK.ID }, true);
    public static final UniqueKey<QuestionGroupRecord> QUESTION_GROUP__ = Internal.createUniqueKey(QuestionGroup.QUESTION_GROUP, DSL.name(""), new TableField[] { QuestionGroup.QUESTION_GROUP.ID }, true);
    public static final UniqueKey<QuestionReferencesRecord> QUESTION_REFERENCES__ = Internal.createUniqueKey(QuestionReferences.QUESTION_REFERENCES, DSL.name(""), new TableField[] { QuestionReferences.QUESTION_REFERENCES.QUESTION_ID, QuestionReferences.QUESTION_REFERENCES.REFERENCE_ID }, true);
    public static final UniqueKey<QuizRecord> QUIZ__ = Internal.createUniqueKey(Quiz.QUIZ, DSL.name(""), new TableField[] { Quiz.QUIZ.ID, Quiz.QUIZ.ID }, true);
    public static final UniqueKey<QuizQuestionsRecord> QUIZ_QUESTIONS__ = Internal.createUniqueKey(QuizQuestions.QUIZ_QUESTIONS, DSL.name(""), new TableField[] { QuizQuestions.QUIZ_QUESTIONS.QUIZ_ID, QuizQuestions.QUIZ_QUESTIONS.QUESTION_ID }, true);
    public static final UniqueKey<QuizReferencesRecord> QUIZ_REFERENCES__ = Internal.createUniqueKey(QuizReferences.QUIZ_REFERENCES, DSL.name(""), new TableField[] { QuizReferences.QUIZ_REFERENCES.QUIZ_ID, QuizReferences.QUIZ_REFERENCES.REFERENCE_ID }, true);
    public static final UniqueKey<ReferenceMaterialRecord> REFERENCE_MATERIAL__ = Internal.createUniqueKey(ReferenceMaterial.REFERENCE_MATERIAL, DSL.name(""), new TableField[] { ReferenceMaterial.REFERENCE_MATERIAL.ID, ReferenceMaterial.REFERENCE_MATERIAL.ID }, true);
    public static final UniqueKey<SectionRecord> SECTION__ = Internal.createUniqueKey(Section.SECTION, DSL.name(""), new TableField[] { Section.SECTION.ID }, true);
}
