/*
 * This file is generated by jOOQ.
 */
package cs499.data_classes.tables.records;


import cs499.data_classes.tables.Metadata;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetadataRecord extends UpdatableRecordImpl<MetadataRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>metadata.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>metadata.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>metadata.quiz_id</code>.
     */
    public void setQuizId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>metadata.quiz_id</code>.
     */
    public Integer getQuizId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>metadata.data</code>.
     */
    public void setData(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>metadata.data</code>.
     */
    public String getData() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Metadata.METADATA.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Metadata.METADATA.QUIZ_ID;
    }

    @Override
    public Field<String> field3() {
        return Metadata.METADATA.DATA;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getQuizId();
    }

    @Override
    public String component3() {
        return getData();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getQuizId();
    }

    @Override
    public String value3() {
        return getData();
    }

    @Override
    public MetadataRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MetadataRecord value2(Integer value) {
        setQuizId(value);
        return this;
    }

    @Override
    public MetadataRecord value3(String value) {
        setData(value);
        return this;
    }

    @Override
    public MetadataRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MetadataRecord
     */
    public MetadataRecord() {
        super(Metadata.METADATA);
    }

    /**
     * Create a detached, initialised MetadataRecord
     */
    public MetadataRecord(Integer id, Integer quizId, String data) {
        super(Metadata.METADATA);

        setId(id);
        setQuizId(quizId);
        setData(data);
    }
}
