/*
 * This file is generated by jOOQ.
 */
package cs499.data_classes.tables.records;


import cs499.data_classes.tables.QuizToQuestion;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizToQuestionRecord extends UpdatableRecordImpl<QuizToQuestionRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>quiz_to_question.quiz_id</code>.
     */
    public void setQuizId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>quiz_to_question.quiz_id</code>.
     */
    public Integer getQuizId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>quiz_to_question.question_id</code>.
     */
    public void setQuestionId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>quiz_to_question.question_id</code>.
     */
    public Integer getQuestionId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return QuizToQuestion.QUIZ_TO_QUESTION.QUIZ_ID;
    }

    @Override
    public Field<Integer> field2() {
        return QuizToQuestion.QUIZ_TO_QUESTION.QUESTION_ID;
    }

    @Override
    public Integer component1() {
        return getQuizId();
    }

    @Override
    public Integer component2() {
        return getQuestionId();
    }

    @Override
    public Integer value1() {
        return getQuizId();
    }

    @Override
    public Integer value2() {
        return getQuestionId();
    }

    @Override
    public QuizToQuestionRecord value1(Integer value) {
        setQuizId(value);
        return this;
    }

    @Override
    public QuizToQuestionRecord value2(Integer value) {
        setQuestionId(value);
        return this;
    }

    @Override
    public QuizToQuestionRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached QuizToQuestionRecord
     */
    public QuizToQuestionRecord() {
        super(QuizToQuestion.QUIZ_TO_QUESTION);
    }

    /**
     * Create a detached, initialised QuizToQuestionRecord
     */
    public QuizToQuestionRecord(Integer quizId, Integer questionId) {
        super(QuizToQuestion.QUIZ_TO_QUESTION);

        setQuizId(quizId);
        setQuestionId(questionId);
    }
}
