//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.04 at 12:42:32 PM CDT 
//


package cs499.qti.data_mapping;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for and_objectsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="and_objectsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="outcomes_metadata" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}outcomes_metadataType"/&gt;
 *         &lt;element name="and_objects" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}and_objectsType"/&gt;
 *         &lt;element name="or_objects" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}or_objectsType"/&gt;
 *         &lt;element name="not_objects" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}not_objectsType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "and_objectsType", propOrder = {
    "outcomesMetadataOrAndObjectsOrOrObjects"
})
public class AndObjectsType {

    @XmlElements({
        @XmlElement(name = "outcomes_metadata", type = OutcomesMetadataType.class),
        @XmlElement(name = "and_objects", type = AndObjectsType.class),
        @XmlElement(name = "or_objects", type = OrObjectsType.class),
        @XmlElement(name = "not_objects", type = NotObjectsType.class)
    })
    protected List<Object> outcomesMetadataOrAndObjectsOrOrObjects;

    /**
     * Gets the value of the outcomesMetadataOrAndObjectsOrOrObjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the outcomesMetadataOrAndObjectsOrOrObjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutcomesMetadataOrAndObjectsOrOrObjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutcomesMetadataType }
     * {@link AndObjectsType }
     * {@link OrObjectsType }
     * {@link NotObjectsType }
     * 
     * 
     */
    public List<Object> getOutcomesMetadataOrAndObjectsOrOrObjects() {
        if (outcomesMetadataOrAndObjectsOrOrObjects == null) {
            outcomesMetadataOrAndObjectsOrOrObjects = new ArrayList<Object>();
        }
        return this.outcomesMetadataOrAndObjectsOrOrObjects;
    }

}
