//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.21 at 06:58:23 PM CDT 
//


package cs499.qti.data_mapping;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for itemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="itemType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="qticomment" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}qticommentType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}duration" minOccurs="0"/&gt;
 *         &lt;element name="itemmetadata" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}itemmetadataType" minOccurs="0"/&gt;
 *         &lt;element name="objectives" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}objectivesType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="itemcontrol" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}itemcontrolType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}itemprecondition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}itempostcondition" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="itemrubric" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}itemrubricType"/&gt;
 *           &lt;element name="rubric" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}rubricType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="presentation" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}presentationType" minOccurs="0"/&gt;
 *         &lt;element name="resprocessing" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}resprocessingType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}itemproc_extension" minOccurs="0"/&gt;
 *         &lt;element name="itemfeedback" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}itemfeedbackType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="reference" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}referenceType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="maxattempts" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ident" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "itemType", propOrder = {
    "qticomment",
    "duration",
    "itemmetadata",
    "objectives",
    "itemcontrol",
    "itemprecondition",
    "itempostcondition",
    "itemrubricOrRubric",
    "presentation",
    "resprocessing",
    "itemprocExtension",
    "itemfeedback",
    "reference"
})
public class ItemType {

    protected QticommentType qticomment;
    protected String duration;
    protected ItemmetadataType itemmetadata;
    protected List<ObjectivesType> objectives;
    protected List<ItemcontrolType> itemcontrol;
    protected List<String> itemprecondition;
    protected List<String> itempostcondition;
    @XmlElements({
        @XmlElement(name = "itemrubric", type = ItemrubricType.class),
        @XmlElement(name = "rubric", type = RubricType.class)
    })
    protected List<Object> itemrubricOrRubric;
    protected PresentationType presentation;
    protected List<ResprocessingType> resprocessing;
    @XmlElement(name = "itemproc_extension")
    protected ItemprocExtensionType itemprocExtension;
    protected List<ItemfeedbackType> itemfeedback;
    protected ReferenceType reference;
    @XmlAttribute(name = "maxattempts")
    protected String maxattempts;
    @XmlAttribute(name = "label")
    protected String label;
    @XmlAttribute(name = "ident", required = true)
    protected String ident;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    /**
     * Gets the value of the qticomment property.
     * 
     * @return
     *     possible object is
     *     {@link QticommentType }
     *     
     */
    public QticommentType getQticomment() {
        return qticomment;
    }

    /**
     * Sets the value of the qticomment property.
     * 
     * @param value
     *     allowed object is
     *     {@link QticommentType }
     *     
     */
    public void setQticomment(QticommentType value) {
        this.qticomment = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the itemmetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ItemmetadataType }
     *     
     */
    public ItemmetadataType getItemmetadata() {
        return itemmetadata;
    }

    /**
     * Sets the value of the itemmetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemmetadataType }
     *     
     */
    public void setItemmetadata(ItemmetadataType value) {
        this.itemmetadata = value;
    }

    /**
     * Gets the value of the objectives property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectives property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectives().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectivesType }
     * 
     * 
     */
    public List<ObjectivesType> getObjectives() {
        if (objectives == null) {
            objectives = new ArrayList<ObjectivesType>();
        }
        return this.objectives;
    }

    /**
     * Gets the value of the itemcontrol property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemcontrol property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemcontrol().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemcontrolType }
     * 
     * 
     */
    public List<ItemcontrolType> getItemcontrol() {
        if (itemcontrol == null) {
            itemcontrol = new ArrayList<ItemcontrolType>();
        }
        return this.itemcontrol;
    }

    /**
     * Gets the value of the itemprecondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemprecondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemprecondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getItemprecondition() {
        if (itemprecondition == null) {
            itemprecondition = new ArrayList<String>();
        }
        return this.itemprecondition;
    }

    /**
     * Gets the value of the itempostcondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itempostcondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItempostcondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getItempostcondition() {
        if (itempostcondition == null) {
            itempostcondition = new ArrayList<String>();
        }
        return this.itempostcondition;
    }

    /**
     * Gets the value of the itemrubricOrRubric property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemrubricOrRubric property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemrubricOrRubric().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemrubricType }
     * {@link RubricType }
     * 
     * 
     */
    public List<Object> getItemrubricOrRubric() {
        if (itemrubricOrRubric == null) {
            itemrubricOrRubric = new ArrayList<Object>();
        }
        return this.itemrubricOrRubric;
    }

    /**
     * Gets the value of the presentation property.
     * 
     * @return
     *     possible object is
     *     {@link PresentationType }
     *     
     */
    public PresentationType getPresentation() {
        return presentation;
    }

    /**
     * Sets the value of the presentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PresentationType }
     *     
     */
    public void setPresentation(PresentationType value) {
        this.presentation = value;
    }

    /**
     * Gets the value of the resprocessing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resprocessing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResprocessing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResprocessingType }
     * 
     * 
     */
    public List<ResprocessingType> getResprocessing() {
        if (resprocessing == null) {
            resprocessing = new ArrayList<ResprocessingType>();
        }
        return this.resprocessing;
    }

    /**
     * Gets the value of the itemprocExtension property.
     * 
     * @return
     *     possible object is
     *     {@link ItemprocExtensionType }
     *     
     */
    public ItemprocExtensionType getItemprocExtension() {
        return itemprocExtension;
    }

    /**
     * Sets the value of the itemprocExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemprocExtensionType }
     *     
     */
    public void setItemprocExtension(ItemprocExtensionType value) {
        this.itemprocExtension = value;
    }

    /**
     * Gets the value of the itemfeedback property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itemfeedback property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItemfeedback().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemfeedbackType }
     * 
     * 
     */
    public List<ItemfeedbackType> getItemfeedback() {
        if (itemfeedback == null) {
            itemfeedback = new ArrayList<ItemfeedbackType>();
        }
        return this.itemfeedback;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setReference(ReferenceType value) {
        this.reference = value;
    }

    /**
     * Gets the value of the maxattempts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxattempts() {
        return maxattempts;
    }

    /**
     * Sets the value of the maxattempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxattempts(String value) {
        this.maxattempts = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the ident property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdent() {
        return ident;
    }

    /**
     * Sets the value of the ident property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdent(String value) {
        this.ident = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

}
