//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.04 at 12:42:32 PM CDT 
//


package cs499.qti.data_mapping;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for not_objectsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="not_objectsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="outcomes_metadata" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}outcomes_metadataType"/&gt;
 *         &lt;element name="and_objects" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}and_objectsType"/&gt;
 *         &lt;element name="or_objects" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}or_objectsType"/&gt;
 *         &lt;element name="not_objects" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}not_objectsType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "not_objectsType", propOrder = {
    "outcomesMetadata",
    "andObjects",
    "orObjects",
    "notObjects"
})
public class NotObjectsType {

    @XmlElement(name = "outcomes_metadata")
    protected OutcomesMetadataType outcomesMetadata;
    @XmlElement(name = "and_objects")
    protected AndObjectsType andObjects;
    @XmlElement(name = "or_objects")
    protected OrObjectsType orObjects;
    @XmlElement(name = "not_objects")
    protected NotObjectsType notObjects;

    /**
     * Gets the value of the outcomesMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link OutcomesMetadataType }
     *     
     */
    public OutcomesMetadataType getOutcomesMetadata() {
        return outcomesMetadata;
    }

    /**
     * Sets the value of the outcomesMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutcomesMetadataType }
     *     
     */
    public void setOutcomesMetadata(OutcomesMetadataType value) {
        this.outcomesMetadata = value;
    }

    /**
     * Gets the value of the andObjects property.
     * 
     * @return
     *     possible object is
     *     {@link AndObjectsType }
     *     
     */
    public AndObjectsType getAndObjects() {
        return andObjects;
    }

    /**
     * Sets the value of the andObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link AndObjectsType }
     *     
     */
    public void setAndObjects(AndObjectsType value) {
        this.andObjects = value;
    }

    /**
     * Gets the value of the orObjects property.
     * 
     * @return
     *     possible object is
     *     {@link OrObjectsType }
     *     
     */
    public OrObjectsType getOrObjects() {
        return orObjects;
    }

    /**
     * Sets the value of the orObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrObjectsType }
     *     
     */
    public void setOrObjects(OrObjectsType value) {
        this.orObjects = value;
    }

    /**
     * Gets the value of the notObjects property.
     * 
     * @return
     *     possible object is
     *     {@link NotObjectsType }
     *     
     */
    public NotObjectsType getNotObjects() {
        return notObjects;
    }

    /**
     * Sets the value of the notObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotObjectsType }
     *     
     */
    public void setNotObjects(NotObjectsType value) {
        this.notObjects = value;
    }

}
