//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.21 at 06:58:23 PM CDT 
//


package cs499.qti.data_mapping;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlMixed;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for response_labelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="response_labelType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="qticomment" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}qticommentType"/&gt;
 *         &lt;element name="material" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}materialType"/&gt;
 *         &lt;element name="material_ref" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}material_refType"/&gt;
 *         &lt;element name="flow_mat" type="{http://www.imsglobal.org/xsd/ims_qtiasiv1p2}flow_matType"/&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="rshuffle" default="Yes"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="Yes"/&gt;
 *             &lt;enumeration value="No"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="rarea" default="Ellipse"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="Ellipse"/&gt;
 *             &lt;enumeration value="Rectangle"/&gt;
 *             &lt;enumeration value="Bounded"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="rrange" default="Exact"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *             &lt;enumeration value="Exact"/&gt;
 *             &lt;enumeration value="Range"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="labelrefid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ident" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="match_group" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="match_max" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "response_labelType", propOrder = {
    "content"
})
public class ResponseLabelType {

    @XmlElementRefs({
        @XmlElementRef(name = "qticomment", namespace = "http://www.imsglobal.org/xsd/ims_qtiasiv1p2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "material", namespace = "http://www.imsglobal.org/xsd/ims_qtiasiv1p2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "material_ref", namespace = "http://www.imsglobal.org/xsd/ims_qtiasiv1p2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "flow_mat", namespace = "http://www.imsglobal.org/xsd/ims_qtiasiv1p2", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "rshuffle")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rshuffle;
    @XmlAttribute(name = "rarea")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rarea;
    @XmlAttribute(name = "rrange")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String rrange;
    @XmlAttribute(name = "labelrefid")
    protected String labelrefid;
    @XmlAttribute(name = "ident", required = true)
    protected String ident;
    @XmlAttribute(name = "match_group")
    protected String matchGroup;
    @XmlAttribute(name = "match_max")
    protected String matchMax;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link QticommentType }{@code >}
     * {@link JAXBElement }{@code <}{@link MaterialType }{@code >}
     * {@link JAXBElement }{@code <}{@link MaterialRefType }{@code >}
     * {@link JAXBElement }{@code <}{@link FlowMatType }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the rshuffle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRshuffle() {
        if (rshuffle == null) {
            return "Yes";
        } else {
            return rshuffle;
        }
    }

    /**
     * Sets the value of the rshuffle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRshuffle(String value) {
        this.rshuffle = value;
    }

    /**
     * Gets the value of the rarea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRarea() {
        if (rarea == null) {
            return "Ellipse";
        } else {
            return rarea;
        }
    }

    /**
     * Sets the value of the rarea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRarea(String value) {
        this.rarea = value;
    }

    /**
     * Gets the value of the rrange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRrange() {
        if (rrange == null) {
            return "Exact";
        } else {
            return rrange;
        }
    }

    /**
     * Sets the value of the rrange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRrange(String value) {
        this.rrange = value;
    }

    /**
     * Gets the value of the labelrefid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelrefid() {
        return labelrefid;
    }

    /**
     * Sets the value of the labelrefid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelrefid(String value) {
        this.labelrefid = value;
    }

    /**
     * Gets the value of the ident property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdent() {
        return ident;
    }

    /**
     * Sets the value of the ident property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdent(String value) {
        this.ident = value;
    }

    /**
     * Gets the value of the matchGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchGroup() {
        return matchGroup;
    }

    /**
     * Sets the value of the matchGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchGroup(String value) {
        this.matchGroup = value;
    }

    /**
     * Gets the value of the matchMax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchMax() {
        return matchMax;
    }

    /**
     * Sets the value of the matchMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchMax(String value) {
        this.matchMax = value;
    }

}
