/*
 * This file is generated by jOOQ.
 */
package cs499.data_classes.tables;


import cs499.data_classes.DefaultSchema;
import cs499.data_classes.Keys;
import cs499.data_classes.tables.records.QuizQuestionsRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class QuizQuestions extends TableImpl<QuizQuestionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>quiz_questions</code>
     */
    public static final QuizQuestions QUIZ_QUESTIONS = new QuizQuestions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<QuizQuestionsRecord> getRecordType() {
        return QuizQuestionsRecord.class;
    }

    /**
     * The column <code>quiz_questions.quiz_id</code>.
     */
    public final TableField<QuizQuestionsRecord, Integer> QUIZ_ID = createField(DSL.name("quiz_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>quiz_questions.question_id</code>.
     */
    public final TableField<QuizQuestionsRecord, Integer> QUESTION_ID = createField(DSL.name("question_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private QuizQuestions(Name alias, Table<QuizQuestionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private QuizQuestions(Name alias, Table<QuizQuestionsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>quiz_questions</code> table reference
     */
    public QuizQuestions(String alias) {
        this(DSL.name(alias), QUIZ_QUESTIONS);
    }

    /**
     * Create an aliased <code>quiz_questions</code> table reference
     */
    public QuizQuestions(Name alias) {
        this(alias, QUIZ_QUESTIONS);
    }

    /**
     * Create a <code>quiz_questions</code> table reference
     */
    public QuizQuestions() {
        this(DSL.name("quiz_questions"), null);
    }

    public <O extends Record> QuizQuestions(Table<O> child, ForeignKey<O, QuizQuestionsRecord> key) {
        super(child, key, QUIZ_QUESTIONS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<QuizQuestionsRecord> getPrimaryKey() {
        return Keys.QUIZ_QUESTIONS__;
    }

    @Override
    public QuizQuestions as(String alias) {
        return new QuizQuestions(DSL.name(alias), this);
    }

    @Override
    public QuizQuestions as(Name alias) {
        return new QuizQuestions(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public QuizQuestions rename(String name) {
        return new QuizQuestions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public QuizQuestions rename(Name name) {
        return new QuizQuestions(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
