//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.06 at 01:47:15 AM CDT 
//


package cs499.qti.package_mapping.imsmd;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lomType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lomType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsmd_v1p2}general" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsmd_v1p2}lifecycle" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsmd_v1p2}metametadata" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsmd_v1p2}technical" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsmd_v1p2}educational" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsmd_v1p2}rights" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsmd_v1p2}relation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsmd_v1p2}annotation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.imsglobal.org/xsd/imsmd_v1p2}classification" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lomType", propOrder = {
    "general",
    "lifecycle",
    "metametadata",
    "technical",
    "educational",
    "rights",
    "relation",
    "annotation",
    "classification"
})
public class LomType {

    protected GeneralType general;
    protected LifecycleType lifecycle;
    protected MetametadataType metametadata;
    protected TechnicalType technical;
    protected EducationalType educational;
    protected RightsType rights;
    protected List<RelationType> relation;
    protected List<AnnotationType> annotation;
    protected List<ClassificationType> classification;

    /**
     * Gets the value of the general property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralType }
     *     
     */
    public GeneralType getGeneral() {
        return general;
    }

    /**
     * Sets the value of the general property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralType }
     *     
     */
    public void setGeneral(GeneralType value) {
        this.general = value;
    }

    /**
     * Gets the value of the lifecycle property.
     * 
     * @return
     *     possible object is
     *     {@link LifecycleType }
     *     
     */
    public LifecycleType getLifecycle() {
        return lifecycle;
    }

    /**
     * Sets the value of the lifecycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link LifecycleType }
     *     
     */
    public void setLifecycle(LifecycleType value) {
        this.lifecycle = value;
    }

    /**
     * Gets the value of the metametadata property.
     * 
     * @return
     *     possible object is
     *     {@link MetametadataType }
     *     
     */
    public MetametadataType getMetametadata() {
        return metametadata;
    }

    /**
     * Sets the value of the metametadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetametadataType }
     *     
     */
    public void setMetametadata(MetametadataType value) {
        this.metametadata = value;
    }

    /**
     * Gets the value of the technical property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalType }
     *     
     */
    public TechnicalType getTechnical() {
        return technical;
    }

    /**
     * Sets the value of the technical property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalType }
     *     
     */
    public void setTechnical(TechnicalType value) {
        this.technical = value;
    }

    /**
     * Gets the value of the educational property.
     * 
     * @return
     *     possible object is
     *     {@link EducationalType }
     *     
     */
    public EducationalType getEducational() {
        return educational;
    }

    /**
     * Sets the value of the educational property.
     * 
     * @param value
     *     allowed object is
     *     {@link EducationalType }
     *     
     */
    public void setEducational(EducationalType value) {
        this.educational = value;
    }

    /**
     * Gets the value of the rights property.
     * 
     * @return
     *     possible object is
     *     {@link RightsType }
     *     
     */
    public RightsType getRights() {
        return rights;
    }

    /**
     * Sets the value of the rights property.
     * 
     * @param value
     *     allowed object is
     *     {@link RightsType }
     *     
     */
    public void setRights(RightsType value) {
        this.rights = value;
    }

    /**
     * Gets the value of the relation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the relation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelationType }
     * 
     * 
     */
    public List<RelationType> getRelation() {
        if (relation == null) {
            relation = new ArrayList<RelationType>();
        }
        return this.relation;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the annotation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnnotation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnnotationType }
     * 
     * 
     */
    public List<AnnotationType> getAnnotation() {
        if (annotation == null) {
            annotation = new ArrayList<AnnotationType>();
        }
        return this.annotation;
    }

    /**
     * Gets the value of the classification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the classification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassificationType }
     * 
     * 
     */
    public List<ClassificationType> getClassification() {
        if (classification == null) {
            classification = new ArrayList<ClassificationType>();
        }
        return this.classification;
    }

}
