//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.06 at 01:47:15 AM CDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.imsglobal.org/xsd/imsmd_v1p2", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cs499.qti.package_mapping.imsmd;
