//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.04 at 12:42:32 PM CDT 
//


package cs499.qti.metadata_mapping;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all minOccurs="0"&gt;
 *         &lt;element name="folders" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="folder" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;all minOccurs="0"&gt;
 *                             &lt;element name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                             &lt;element name="locked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                             &lt;element name="lock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
 *                             &lt;element name="unlock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
 *                           &lt;/all&gt;
 *                           &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="files" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="file" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;all minOccurs="0"&gt;
 *                             &lt;element name="display_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                             &lt;element name="locked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *                             &lt;element name="lock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
 *                             &lt;element name="unlock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
 *                             &lt;element name="usage_rights" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;all minOccurs="0"&gt;
 *                                       &lt;element name="legal_copyright" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="license" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                     &lt;/all&gt;
 *                                     &lt;attribute name="use_justification" use="required"&gt;
 *                                       &lt;simpleType&gt;
 *                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                                           &lt;enumeration value="public_domain"/&gt;
 *                                           &lt;enumeration value="own_copyright"/&gt;
 *                                           &lt;enumeration value="used_by_permission"/&gt;
 *                                           &lt;enumeration value="fair_use"/&gt;
 *                                           &lt;enumeration value="creative_commons"/&gt;
 *                                         &lt;/restriction&gt;
 *                                       &lt;/simpleType&gt;
 *                                     &lt;/attribute&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/all&gt;
 *                           &lt;attribute name="identifier" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "fileMeta")
public class FileMeta {

    protected FileMeta.Folders folders;
    protected FileMeta.Files files;

    /**
     * Gets the value of the folders property.
     * 
     * @return
     *     possible object is
     *     {@link FileMeta.Folders }
     *     
     */
    public FileMeta.Folders getFolders() {
        return folders;
    }

    /**
     * Sets the value of the folders property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileMeta.Folders }
     *     
     */
    public void setFolders(FileMeta.Folders value) {
        this.folders = value;
    }

    /**
     * Gets the value of the files property.
     * 
     * @return
     *     possible object is
     *     {@link FileMeta.Files }
     *     
     */
    public FileMeta.Files getFiles() {
        return files;
    }

    /**
     * Sets the value of the files property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileMeta.Files }
     *     
     */
    public void setFiles(FileMeta.Files value) {
        this.files = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="file" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;all minOccurs="0"&gt;
     *                   &lt;element name="display_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *                   &lt;element name="locked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *                   &lt;element name="lock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
     *                   &lt;element name="unlock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
     *                   &lt;element name="usage_rights" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;all minOccurs="0"&gt;
     *                             &lt;element name="legal_copyright" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                             &lt;element name="license" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                           &lt;/all&gt;
     *                           &lt;attribute name="use_justification" use="required"&gt;
     *                             &lt;simpleType&gt;
     *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *                                 &lt;enumeration value="public_domain"/&gt;
     *                                 &lt;enumeration value="own_copyright"/&gt;
     *                                 &lt;enumeration value="used_by_permission"/&gt;
     *                                 &lt;enumeration value="fair_use"/&gt;
     *                                 &lt;enumeration value="creative_commons"/&gt;
     *                               &lt;/restriction&gt;
     *                             &lt;/simpleType&gt;
     *                           &lt;/attribute&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/all&gt;
     *                 &lt;attribute name="identifier" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "file"
    })
    public static class Files {

        protected List<FileMeta.Files.File> file;

        /**
         * Gets the value of the file property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the file property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FileMeta.Files.File }
         * 
         * 
         */
        public List<FileMeta.Files.File> getFile() {
            if (file == null) {
                file = new ArrayList<FileMeta.Files.File>();
            }
            return this.file;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;all minOccurs="0"&gt;
         *         &lt;element name="display_name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
         *         &lt;element name="locked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
         *         &lt;element name="lock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
         *         &lt;element name="unlock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
         *         &lt;element name="usage_rights" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;all minOccurs="0"&gt;
         *                   &lt;element name="legal_copyright" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                   &lt;element name="license" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                 &lt;/all&gt;
         *                 &lt;attribute name="use_justification" use="required"&gt;
         *                   &lt;simpleType&gt;
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
         *                       &lt;enumeration value="public_domain"/&gt;
         *                       &lt;enumeration value="own_copyright"/&gt;
         *                       &lt;enumeration value="used_by_permission"/&gt;
         *                       &lt;enumeration value="fair_use"/&gt;
         *                       &lt;enumeration value="creative_commons"/&gt;
         *                     &lt;/restriction&gt;
         *                   &lt;/simpleType&gt;
         *                 &lt;/attribute&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/all&gt;
         *       &lt;attribute name="identifier" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class File {

            @XmlElement(name = "display_name")
            protected String displayName;
            protected Boolean hidden;
            protected Boolean locked;
            @XmlElement(name = "lock_at")
            protected String lockAt;
            @XmlElement(name = "unlock_at")
            protected String unlockAt;
            @XmlElement(name = "usage_rights")
            protected FileMeta.Files.File.UsageRights usageRights;
            @XmlAttribute(name = "identifier", required = true)
            protected String identifier;

            /**
             * Gets the value of the displayName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDisplayName() {
                return displayName;
            }

            /**
             * Sets the value of the displayName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDisplayName(String value) {
                this.displayName = value;
            }

            /**
             * Gets the value of the hidden property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isHidden() {
                return hidden;
            }

            /**
             * Sets the value of the hidden property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setHidden(Boolean value) {
                this.hidden = value;
            }

            /**
             * Gets the value of the locked property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isLocked() {
                return locked;
            }

            /**
             * Sets the value of the locked property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setLocked(Boolean value) {
                this.locked = value;
            }

            /**
             * Gets the value of the lockAt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLockAt() {
                return lockAt;
            }

            /**
             * Sets the value of the lockAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLockAt(String value) {
                this.lockAt = value;
            }

            /**
             * Gets the value of the unlockAt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnlockAt() {
                return unlockAt;
            }

            /**
             * Sets the value of the unlockAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnlockAt(String value) {
                this.unlockAt = value;
            }

            /**
             * Gets the value of the usageRights property.
             * 
             * @return
             *     possible object is
             *     {@link FileMeta.Files.File.UsageRights }
             *     
             */
            public FileMeta.Files.File.UsageRights getUsageRights() {
                return usageRights;
            }

            /**
             * Sets the value of the usageRights property.
             * 
             * @param value
             *     allowed object is
             *     {@link FileMeta.Files.File.UsageRights }
             *     
             */
            public void setUsageRights(FileMeta.Files.File.UsageRights value) {
                this.usageRights = value;
            }

            /**
             * Gets the value of the identifier property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIdentifier() {
                return identifier;
            }

            /**
             * Sets the value of the identifier property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIdentifier(String value) {
                this.identifier = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;all minOccurs="0"&gt;
             *         &lt;element name="legal_copyright" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *         &lt;element name="license" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *       &lt;/all&gt;
             *       &lt;attribute name="use_justification" use="required"&gt;
             *         &lt;simpleType&gt;
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
             *             &lt;enumeration value="public_domain"/&gt;
             *             &lt;enumeration value="own_copyright"/&gt;
             *             &lt;enumeration value="used_by_permission"/&gt;
             *             &lt;enumeration value="fair_use"/&gt;
             *             &lt;enumeration value="creative_commons"/&gt;
             *           &lt;/restriction&gt;
             *         &lt;/simpleType&gt;
             *       &lt;/attribute&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {

            })
            public static class UsageRights {

                @XmlElement(name = "legal_copyright")
                protected String legalCopyright;
                protected String license;
                @XmlAttribute(name = "use_justification", required = true)
                protected String useJustification;

                /**
                 * Gets the value of the legalCopyright property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLegalCopyright() {
                    return legalCopyright;
                }

                /**
                 * Sets the value of the legalCopyright property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLegalCopyright(String value) {
                    this.legalCopyright = value;
                }

                /**
                 * Gets the value of the license property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLicense() {
                    return license;
                }

                /**
                 * Sets the value of the license property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLicense(String value) {
                    this.license = value;
                }

                /**
                 * Gets the value of the useJustification property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUseJustification() {
                    return useJustification;
                }

                /**
                 * Sets the value of the useJustification property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUseJustification(String value) {
                    this.useJustification = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="folder" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;all minOccurs="0"&gt;
     *                   &lt;element name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *                   &lt;element name="locked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
     *                   &lt;element name="lock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
     *                   &lt;element name="unlock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
     *                 &lt;/all&gt;
     *                 &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "folder"
    })
    public static class Folders {

        protected List<FileMeta.Folders.Folder> folder;

        /**
         * Gets the value of the folder property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the folder property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFolder().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FileMeta.Folders.Folder }
         * 
         * 
         */
        public List<FileMeta.Folders.Folder> getFolder() {
            if (folder == null) {
                folder = new ArrayList<FileMeta.Folders.Folder>();
            }
            return this.folder;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;all minOccurs="0"&gt;
         *         &lt;element name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
         *         &lt;element name="locked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
         *         &lt;element name="lock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
         *         &lt;element name="unlock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
         *       &lt;/all&gt;
         *       &lt;attribute name="path" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Folder {

            protected Boolean hidden;
            protected Boolean locked;
            @XmlElement(name = "lock_at")
            protected String lockAt;
            @XmlElement(name = "unlock_at")
            protected String unlockAt;
            @XmlAttribute(name = "path", required = true)
            protected String path;

            /**
             * Gets the value of the hidden property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isHidden() {
                return hidden;
            }

            /**
             * Sets the value of the hidden property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setHidden(Boolean value) {
                this.hidden = value;
            }

            /**
             * Gets the value of the locked property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isLocked() {
                return locked;
            }

            /**
             * Sets the value of the locked property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setLocked(Boolean value) {
                this.locked = value;
            }

            /**
             * Gets the value of the lockAt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLockAt() {
                return lockAt;
            }

            /**
             * Sets the value of the lockAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLockAt(String value) {
                this.lockAt = value;
            }

            /**
             * Gets the value of the unlockAt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnlockAt() {
                return unlockAt;
            }

            /**
             * Sets the value of the unlockAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnlockAt(String value) {
                this.unlockAt = value;
            }

            /**
             * Gets the value of the path property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPath() {
                return path;
            }

            /**
             * Sets the value of the path property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPath(String value) {
                this.path = value;
            }

        }

    }

}
