//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.04 at 12:42:32 PM CDT 
//


package cs499.qti.metadata_mapping;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for latePolicyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="latePolicyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all minOccurs="0"&gt;
 *         &lt;element name="missing_submission_deduction_enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="missing_submission_deduction" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_float" minOccurs="0"/&gt;
 *         &lt;element name="late_submission_deduction_enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="late_submission_deduction" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_float" minOccurs="0"/&gt;
 *         &lt;element name="late_submission_interval" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="late_submission_minimum_percent_enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="late_submission_minimum_percent" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_float" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "latePolicyType", propOrder = {

})
public class LatePolicyType {

    @XmlElement(name = "missing_submission_deduction_enabled")
    protected Boolean missingSubmissionDeductionEnabled;
    @XmlElement(name = "missing_submission_deduction")
    protected String missingSubmissionDeduction;
    @XmlElement(name = "late_submission_deduction_enabled")
    protected Boolean lateSubmissionDeductionEnabled;
    @XmlElement(name = "late_submission_deduction")
    protected String lateSubmissionDeduction;
    @XmlElement(name = "late_submission_interval")
    protected String lateSubmissionInterval;
    @XmlElement(name = "late_submission_minimum_percent_enabled")
    protected Boolean lateSubmissionMinimumPercentEnabled;
    @XmlElement(name = "late_submission_minimum_percent")
    protected String lateSubmissionMinimumPercent;

    /**
     * Gets the value of the missingSubmissionDeductionEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMissingSubmissionDeductionEnabled() {
        return missingSubmissionDeductionEnabled;
    }

    /**
     * Sets the value of the missingSubmissionDeductionEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMissingSubmissionDeductionEnabled(Boolean value) {
        this.missingSubmissionDeductionEnabled = value;
    }

    /**
     * Gets the value of the missingSubmissionDeduction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMissingSubmissionDeduction() {
        return missingSubmissionDeduction;
    }

    /**
     * Sets the value of the missingSubmissionDeduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMissingSubmissionDeduction(String value) {
        this.missingSubmissionDeduction = value;
    }

    /**
     * Gets the value of the lateSubmissionDeductionEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLateSubmissionDeductionEnabled() {
        return lateSubmissionDeductionEnabled;
    }

    /**
     * Sets the value of the lateSubmissionDeductionEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLateSubmissionDeductionEnabled(Boolean value) {
        this.lateSubmissionDeductionEnabled = value;
    }

    /**
     * Gets the value of the lateSubmissionDeduction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLateSubmissionDeduction() {
        return lateSubmissionDeduction;
    }

    /**
     * Sets the value of the lateSubmissionDeduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLateSubmissionDeduction(String value) {
        this.lateSubmissionDeduction = value;
    }

    /**
     * Gets the value of the lateSubmissionInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLateSubmissionInterval() {
        return lateSubmissionInterval;
    }

    /**
     * Sets the value of the lateSubmissionInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLateSubmissionInterval(String value) {
        this.lateSubmissionInterval = value;
    }

    /**
     * Gets the value of the lateSubmissionMinimumPercentEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLateSubmissionMinimumPercentEnabled() {
        return lateSubmissionMinimumPercentEnabled;
    }

    /**
     * Sets the value of the lateSubmissionMinimumPercentEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLateSubmissionMinimumPercentEnabled(Boolean value) {
        this.lateSubmissionMinimumPercentEnabled = value;
    }

    /**
     * Gets the value of the lateSubmissionMinimumPercent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLateSubmissionMinimumPercent() {
        return lateSubmissionMinimumPercent;
    }

    /**
     * Sets the value of the lateSubmissionMinimumPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLateSubmissionMinimumPercent(String value) {
        this.lateSubmissionMinimumPercent = value;
    }

}
