//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.05 at 04:00:55 PM CDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://canvas.instructure.com/xsd/cccv1p0", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cs499.qti.metadata_mapping;
