//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.05 at 04:00:55 PM CDT 
//


package cs499.qti.metadata_mapping;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all minOccurs="0"&gt;
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="points_possible" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_float" minOccurs="0"/&gt;
 *         &lt;element name="assignment" type="{http://canvas.instructure.com/xsd/cccv1p0}assignmentType" minOccurs="0"/&gt;
 *         &lt;element name="lock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
 *         &lt;element name="unlock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
 *         &lt;element name="module_locked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="due_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
 *         &lt;element name="shuffle_answers" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="hide_results" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="require_lockdown_browser" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="require_lockdown_browser_for_results" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="require_lockdown_browser_monitor" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="lockdown_browser_monitor_data" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="access_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ip_filter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="show_correct_answers" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="show_correct_answers_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
 *         &lt;element name="hide_correct_answers_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" minOccurs="0"/&gt;
 *         &lt;element name="anonymous_submissions" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="could_be_locked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="available" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="time_limit" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_integer" minOccurs="0"/&gt;
 *         &lt;element name="disable_timer_autosubmission" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="allowed_attempts" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_integer" minOccurs="0"/&gt;
 *         &lt;element name="one_question_at_a_time" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="cant_go_back" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="one_time_results" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="show_correct_answers_last_attempt" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="only_visible_to_overrides" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="assignment_group_identifierref" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="quiz_type" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="practice_quiz"/&gt;
 *               &lt;enumeration value="assignment"/&gt;
 *               &lt;enumeration value="graded_survey"/&gt;
 *               &lt;enumeration value="survey"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="scoring_policy" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="keep_latest"/&gt;
 *               &lt;enumeration value="keep_highest"/&gt;
 *               &lt;enumeration value="keep_average"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="assignment_overrides" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;element name="override"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="set_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="set_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="due_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" /&gt;
 *                           &lt;attribute name="unlock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" /&gt;
 *                           &lt;attribute name="lock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" /&gt;
 *                           &lt;attribute name="due_at_overridden" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="unlock_at_overridden" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                           &lt;attribute name="lock_at_overridden" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="identifier" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "quiz")
public class Quiz {

    protected String title;
    protected String description;
    @XmlElement(name = "points_possible")
    protected String pointsPossible;
    protected AssignmentType assignment;
    @XmlElement(name = "lock_at")
    protected String lockAt;
    @XmlElement(name = "unlock_at")
    protected String unlockAt;
    @XmlElement(name = "module_locked")
    protected Boolean moduleLocked;
    @XmlElement(name = "due_at")
    protected String dueAt;
    @XmlElement(name = "shuffle_answers")
    protected Boolean shuffleAnswers;
    @XmlElement(name = "hide_results")
    protected String hideResults;
    @XmlElement(name = "require_lockdown_browser")
    protected Boolean requireLockdownBrowser;
    @XmlElement(name = "require_lockdown_browser_for_results")
    protected Boolean requireLockdownBrowserForResults;
    @XmlElement(name = "require_lockdown_browser_monitor")
    protected Boolean requireLockdownBrowserMonitor;
    @XmlElement(name = "lockdown_browser_monitor_data")
    protected String lockdownBrowserMonitorData;
    @XmlElement(name = "access_code")
    protected String accessCode;
    @XmlElement(name = "ip_filter")
    protected String ipFilter;
    @XmlElement(name = "show_correct_answers")
    protected Boolean showCorrectAnswers;
    @XmlElement(name = "show_correct_answers_at")
    protected String showCorrectAnswersAt;
    @XmlElement(name = "hide_correct_answers_at")
    protected String hideCorrectAnswersAt;
    @XmlElement(name = "anonymous_submissions")
    protected Boolean anonymousSubmissions;
    @XmlElement(name = "could_be_locked")
    protected Boolean couldBeLocked;
    protected Boolean available;
    @XmlElement(name = "time_limit")
    protected String timeLimit;
    @XmlElement(name = "disable_timer_autosubmission")
    protected Boolean disableTimerAutosubmission;
    @XmlElement(name = "allowed_attempts")
    protected String allowedAttempts;
    @XmlElement(name = "one_question_at_a_time")
    protected Boolean oneQuestionAtATime;
    @XmlElement(name = "cant_go_back")
    protected Boolean cantGoBack;
    @XmlElement(name = "one_time_results")
    protected Boolean oneTimeResults;
    @XmlElement(name = "show_correct_answers_last_attempt")
    protected Boolean showCorrectAnswersLastAttempt;
    @XmlElement(name = "only_visible_to_overrides")
    protected Boolean onlyVisibleToOverrides;
    @XmlElement(name = "assignment_group_identifierref")
    protected String assignmentGroupIdentifierref;
    @XmlElement(name = "quiz_type", defaultValue = "practice_quiz")
    protected String quizType;
    @XmlElement(name = "scoring_policy", defaultValue = "keep_highest")
    protected String scoringPolicy;
    @XmlElement(name = "assignment_overrides")
    protected Quiz.AssignmentOverrides assignmentOverrides;
    @XmlAttribute(name = "identifier", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String identifier;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the pointsPossible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointsPossible() {
        return pointsPossible;
    }

    /**
     * Sets the value of the pointsPossible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointsPossible(String value) {
        this.pointsPossible = value;
    }

    /**
     * Gets the value of the assignment property.
     * 
     * @return
     *     possible object is
     *     {@link AssignmentType }
     *     
     */
    public AssignmentType getAssignment() {
        return assignment;
    }

    /**
     * Sets the value of the assignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssignmentType }
     *     
     */
    public void setAssignment(AssignmentType value) {
        this.assignment = value;
    }

    /**
     * Gets the value of the lockAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLockAt() {
        return lockAt;
    }

    /**
     * Sets the value of the lockAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLockAt(String value) {
        this.lockAt = value;
    }

    /**
     * Gets the value of the unlockAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnlockAt() {
        return unlockAt;
    }

    /**
     * Sets the value of the unlockAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnlockAt(String value) {
        this.unlockAt = value;
    }

    /**
     * Gets the value of the moduleLocked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isModuleLocked() {
        return moduleLocked;
    }

    /**
     * Sets the value of the moduleLocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setModuleLocked(Boolean value) {
        this.moduleLocked = value;
    }

    /**
     * Gets the value of the dueAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueAt() {
        return dueAt;
    }

    /**
     * Sets the value of the dueAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueAt(String value) {
        this.dueAt = value;
    }

    /**
     * Gets the value of the shuffleAnswers property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShuffleAnswers() {
        return shuffleAnswers;
    }

    /**
     * Sets the value of the shuffleAnswers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShuffleAnswers(Boolean value) {
        this.shuffleAnswers = value;
    }

    /**
     * Gets the value of the hideResults property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHideResults() {
        return hideResults;
    }

    /**
     * Sets the value of the hideResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHideResults(String value) {
        this.hideResults = value;
    }

    /**
     * Gets the value of the requireLockdownBrowser property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequireLockdownBrowser() {
        return requireLockdownBrowser;
    }

    /**
     * Sets the value of the requireLockdownBrowser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequireLockdownBrowser(Boolean value) {
        this.requireLockdownBrowser = value;
    }

    /**
     * Gets the value of the requireLockdownBrowserForResults property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequireLockdownBrowserForResults() {
        return requireLockdownBrowserForResults;
    }

    /**
     * Sets the value of the requireLockdownBrowserForResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequireLockdownBrowserForResults(Boolean value) {
        this.requireLockdownBrowserForResults = value;
    }

    /**
     * Gets the value of the requireLockdownBrowserMonitor property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequireLockdownBrowserMonitor() {
        return requireLockdownBrowserMonitor;
    }

    /**
     * Sets the value of the requireLockdownBrowserMonitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequireLockdownBrowserMonitor(Boolean value) {
        this.requireLockdownBrowserMonitor = value;
    }

    /**
     * Gets the value of the lockdownBrowserMonitorData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLockdownBrowserMonitorData() {
        return lockdownBrowserMonitorData;
    }

    /**
     * Sets the value of the lockdownBrowserMonitorData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLockdownBrowserMonitorData(String value) {
        this.lockdownBrowserMonitorData = value;
    }

    /**
     * Gets the value of the accessCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessCode() {
        return accessCode;
    }

    /**
     * Sets the value of the accessCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessCode(String value) {
        this.accessCode = value;
    }

    /**
     * Gets the value of the ipFilter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIpFilter() {
        return ipFilter;
    }

    /**
     * Sets the value of the ipFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIpFilter(String value) {
        this.ipFilter = value;
    }

    /**
     * Gets the value of the showCorrectAnswers property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowCorrectAnswers() {
        return showCorrectAnswers;
    }

    /**
     * Sets the value of the showCorrectAnswers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowCorrectAnswers(Boolean value) {
        this.showCorrectAnswers = value;
    }

    /**
     * Gets the value of the showCorrectAnswersAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowCorrectAnswersAt() {
        return showCorrectAnswersAt;
    }

    /**
     * Sets the value of the showCorrectAnswersAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowCorrectAnswersAt(String value) {
        this.showCorrectAnswersAt = value;
    }

    /**
     * Gets the value of the hideCorrectAnswersAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHideCorrectAnswersAt() {
        return hideCorrectAnswersAt;
    }

    /**
     * Sets the value of the hideCorrectAnswersAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHideCorrectAnswersAt(String value) {
        this.hideCorrectAnswersAt = value;
    }

    /**
     * Gets the value of the anonymousSubmissions property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAnonymousSubmissions() {
        return anonymousSubmissions;
    }

    /**
     * Sets the value of the anonymousSubmissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAnonymousSubmissions(Boolean value) {
        this.anonymousSubmissions = value;
    }

    /**
     * Gets the value of the couldBeLocked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCouldBeLocked() {
        return couldBeLocked;
    }

    /**
     * Sets the value of the couldBeLocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCouldBeLocked(Boolean value) {
        this.couldBeLocked = value;
    }

    /**
     * Gets the value of the available property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAvailable() {
        return available;
    }

    /**
     * Sets the value of the available property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAvailable(Boolean value) {
        this.available = value;
    }

    /**
     * Gets the value of the timeLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeLimit() {
        return timeLimit;
    }

    /**
     * Sets the value of the timeLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeLimit(String value) {
        this.timeLimit = value;
    }

    /**
     * Gets the value of the disableTimerAutosubmission property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisableTimerAutosubmission() {
        return disableTimerAutosubmission;
    }

    /**
     * Sets the value of the disableTimerAutosubmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisableTimerAutosubmission(Boolean value) {
        this.disableTimerAutosubmission = value;
    }

    /**
     * Gets the value of the allowedAttempts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowedAttempts() {
        return allowedAttempts;
    }

    /**
     * Sets the value of the allowedAttempts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowedAttempts(String value) {
        this.allowedAttempts = value;
    }

    /**
     * Gets the value of the oneQuestionAtATime property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOneQuestionAtATime() {
        return oneQuestionAtATime;
    }

    /**
     * Sets the value of the oneQuestionAtATime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOneQuestionAtATime(Boolean value) {
        this.oneQuestionAtATime = value;
    }

    /**
     * Gets the value of the cantGoBack property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCantGoBack() {
        return cantGoBack;
    }

    /**
     * Sets the value of the cantGoBack property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCantGoBack(Boolean value) {
        this.cantGoBack = value;
    }

    /**
     * Gets the value of the oneTimeResults property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOneTimeResults() {
        return oneTimeResults;
    }

    /**
     * Sets the value of the oneTimeResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOneTimeResults(Boolean value) {
        this.oneTimeResults = value;
    }

    /**
     * Gets the value of the showCorrectAnswersLastAttempt property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowCorrectAnswersLastAttempt() {
        return showCorrectAnswersLastAttempt;
    }

    /**
     * Sets the value of the showCorrectAnswersLastAttempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowCorrectAnswersLastAttempt(Boolean value) {
        this.showCorrectAnswersLastAttempt = value;
    }

    /**
     * Gets the value of the onlyVisibleToOverrides property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOnlyVisibleToOverrides() {
        return onlyVisibleToOverrides;
    }

    /**
     * Sets the value of the onlyVisibleToOverrides property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOnlyVisibleToOverrides(Boolean value) {
        this.onlyVisibleToOverrides = value;
    }

    /**
     * Gets the value of the assignmentGroupIdentifierref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignmentGroupIdentifierref() {
        return assignmentGroupIdentifierref;
    }

    /**
     * Sets the value of the assignmentGroupIdentifierref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignmentGroupIdentifierref(String value) {
        this.assignmentGroupIdentifierref = value;
    }

    /**
     * Gets the value of the quizType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuizType() {
        return quizType;
    }

    /**
     * Sets the value of the quizType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuizType(String value) {
        this.quizType = value;
    }

    /**
     * Gets the value of the scoringPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScoringPolicy() {
        return scoringPolicy;
    }

    /**
     * Sets the value of the scoringPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScoringPolicy(String value) {
        this.scoringPolicy = value;
    }

    /**
     * Gets the value of the assignmentOverrides property.
     * 
     * @return
     *     possible object is
     *     {@link Quiz.AssignmentOverrides }
     *     
     */
    public Quiz.AssignmentOverrides getAssignmentOverrides() {
        return assignmentOverrides;
    }

    /**
     * Sets the value of the assignmentOverrides property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quiz.AssignmentOverrides }
     *     
     */
    public void setAssignmentOverrides(Quiz.AssignmentOverrides value) {
        this.assignmentOverrides = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;element name="override"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="set_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="set_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="due_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" /&gt;
     *                 &lt;attribute name="unlock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" /&gt;
     *                 &lt;attribute name="lock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" /&gt;
     *                 &lt;attribute name="due_at_overridden" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="unlock_at_overridden" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *                 &lt;attribute name="lock_at_overridden" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "override"
    })
    public static class AssignmentOverrides {

        protected List<Quiz.AssignmentOverrides.Override> override;

        /**
         * Gets the value of the override property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the override property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOverride().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Quiz.AssignmentOverrides.Override }
         * 
         * 
         */
        public List<Quiz.AssignmentOverrides.Override> getOverride() {
            if (override == null) {
                override = new ArrayList<Quiz.AssignmentOverrides.Override>();
            }
            return this.override;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="set_type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="set_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="due_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" /&gt;
         *       &lt;attribute name="unlock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" /&gt;
         *       &lt;attribute name="lock_at" type="{http://canvas.instructure.com/xsd/cccv1p0}optional_dateTime" /&gt;
         *       &lt;attribute name="due_at_overridden" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="unlock_at_overridden" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *       &lt;attribute name="lock_at_overridden" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Override {

            @XmlAttribute(name = "set_type", required = true)
            protected String setType;
            @XmlAttribute(name = "set_id", required = true)
            protected String setId;
            @XmlAttribute(name = "title", required = true)
            protected String title;
            @XmlAttribute(name = "due_at")
            protected String dueAt;
            @XmlAttribute(name = "unlock_at")
            protected String unlockAt;
            @XmlAttribute(name = "lock_at")
            protected String lockAt;
            @XmlAttribute(name = "due_at_overridden")
            protected Boolean dueAtOverridden;
            @XmlAttribute(name = "unlock_at_overridden")
            protected Boolean unlockAtOverridden;
            @XmlAttribute(name = "lock_at_overridden")
            protected Boolean lockAtOverridden;

            /**
             * Gets the value of the setType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSetType() {
                return setType;
            }

            /**
             * Sets the value of the setType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSetType(String value) {
                this.setType = value;
            }

            /**
             * Gets the value of the setId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSetId() {
                return setId;
            }

            /**
             * Sets the value of the setId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSetId(String value) {
                this.setId = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the dueAt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDueAt() {
                return dueAt;
            }

            /**
             * Sets the value of the dueAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDueAt(String value) {
                this.dueAt = value;
            }

            /**
             * Gets the value of the unlockAt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnlockAt() {
                return unlockAt;
            }

            /**
             * Sets the value of the unlockAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnlockAt(String value) {
                this.unlockAt = value;
            }

            /**
             * Gets the value of the lockAt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLockAt() {
                return lockAt;
            }

            /**
             * Sets the value of the lockAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLockAt(String value) {
                this.lockAt = value;
            }

            /**
             * Gets the value of the dueAtOverridden property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isDueAtOverridden() {
                return dueAtOverridden;
            }

            /**
             * Sets the value of the dueAtOverridden property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setDueAtOverridden(Boolean value) {
                this.dueAtOverridden = value;
            }

            /**
             * Gets the value of the unlockAtOverridden property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isUnlockAtOverridden() {
                return unlockAtOverridden;
            }

            /**
             * Sets the value of the unlockAtOverridden property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setUnlockAtOverridden(Boolean value) {
                this.unlockAtOverridden = value;
            }

            /**
             * Gets the value of the lockAtOverridden property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isLockAtOverridden() {
                return lockAtOverridden;
            }

            /**
             * Sets the value of the lockAtOverridden property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setLockAtOverridden(Boolean value) {
                this.lockAtOverridden = value;
            }

        }

    }

}
