//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.05 at 01:46:08 PM CDT 
//


package cs499.qti.package_mapping.lomresource;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 *                 The LOM complexType is the container for the metadata instance.
 * 
 * CC Resource Profile - only a single Educational element is permitted.
 *             
 * 
 * <p>Java class for LOM.Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LOM.Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="educational" type="{http://ltsc.ieee.org/xsd/imsccv1p1/LOM/resource}Educational.Type" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LOM.Type", propOrder = {
    "educational"
})
public class LOMType {

    @XmlElement(required = true)
    protected List<EducationalType> educational;

    /**
     * Gets the value of the educational property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the educational property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEducational().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EducationalType }
     * 
     * 
     */
    public List<EducationalType> getEducational() {
        if (educational == null) {
            educational = new ArrayList<EducationalType>();
        }
        return this.educational;
    }

}
